### ISSUE TITLE
in-fset error

### ISSUE THREAD

**Issue by djpeebles** [blake-watkins/advent-of-code#1]
When loading this for the first time I get the following error...

in: DEFUN MAP-DIMENSIONS
;     (ITERATE:ITER
;       (ITERATE:WITH MAX = (FSET:ARB MAP))
;       (ITERATE:FOR ADVENT-OF-CODE::POS ADVENT-OF-CODE::IN-FSET MAP)
;       (SETF MAX (MAPCAR #'MAX ADVENT-OF-CODE::POS MAX))
;       (ITERATE:FINALLY (RETURN MAX)))
; 
; caught ERROR:
;   during macroexpansion of
;   (ITER
;     (WITH MAX = ...)
;     (FOR POS IN-FSET ...)
;     ...).
;   Use *BREAK-ON-SIGNALS* to intercept.
;   
;    Iterate, in (FOR POS IN-FSET MAP):
;   Unknown keyword IN-FSET
; 
; compilation unit aborted
;   caught 1 fatal ERROR condition
;   caught 1 ERROR condition
; Evaluation aborted on #<UIOP/LISP-BUILD:COMPILE-FILE-ERROR {1016A56583}>.

**Comment by blake-watkins** [comment]
Thanks for the issue. I think it's because I'd forgotten to add the days for 2021 into the .asd file so they weren't loading the AOC package properly. IN-FSET is a clause for the ITER macro that is in the util.lisp file. It gets items from an fset collection to be used in an iterate form.

I've updated the asd file so it should work now.
